name: Build Windows (MSYS2)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-qt6-base
            mingw-w64-ucrt-x86_64-minizip
            make

      - name: Build project
        run: |
          mkdir build
          cd build
          qmake6 ../DoomRunner.pro CONFIG+=release
          make -j$(nproc)

      - name: Prepare Deployment
        run: |
          DEPLOY_PATH="$(pwd)/deploy"
          mkdir -p "$DEPLOY_PATH"
          EXE_FILE="build/release/DoomRunner.exe"
          
          # 1. Копируем сам экзешник
          cp "$EXE_FILE" "$DEPLOY_PATH/"
          
          # 2. Умное копирование зависимостей через ldd
          # Эта команда находит все DLL, от которых зависит проект в среде MSYS2, и копирует их
          ldd "$EXE_FILE" | grep /ucrt64/ | awk '{print $3}' | xargs -I{} cp {} "$DEPLOY_PATH/"
          
          # 3. Деплой ресурсов Qt (плагины, платформы)
          windeployqt --release --no-translations --no-compiler-runtime "$DEPLOY_PATH/DoomRunner.exe"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DoomRunner-Final-Pack
          path: deploy/
